services:
  nginx:
    image:  requirements/nginx
    networks:
      - docker-network
    volumes:
      - wordpress-data
    depends_on:
      - wordpress

  mariadb:
    image:  requirements/mariadb
    networks:
      - docker-network
      volumes:
      - mariadb-data
    secrets:
      - db_password
      - db_root_password

  wordpress:
    image:  requirements/wordpress
    networks:
      - docker-network
    volumes:
      - wordpress-data
    depends_on:
      - mariadb

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local

networks:
  docker-network: {}

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
