name: inception

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
    networks:
      - docker-network
    volumes:
      - wordpress-data:/usr/share/webapps/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    expose:
      - "9000"
    secrets:
      - server_key
      - server_cert

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
    env_file: mariadb.env
    networks:
      - docker-network
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "db_ready"]
      interval: 10s
      timeout: 10s
      retries: 5
    secrets:
      - db_password
      - db_root_password

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: wordpress.env
    networks:
      - docker-network
    volumes:
      - wordpress-data:/usr/share/webapps/
    expose:
      - "3306"
      - "9000"
    secrets:
      - db_password
      - wp_author_password

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db-data
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress-data

networks:
  docker-network: {}

secrets:
  wp_author_password:
    file: ../secrets/wp_author_password.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  server_key:
    file: ../secrets/server.key
  server_cert:
    file: ../secrets/server.crt
